# Generated by Django 4.2.8 on 2024-01-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AviationFleetMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('view_asset_avmfs', 'Can view asset'), ('edit_asset_avmfs', 'Can edit asset'), ('add_asset_avmfs', 'Can add asset'), ('delete_asset_avmfs', 'Can delete asset')]},
        ),
        migrations.AlterModelOptions(
            name='carbonemissions',
            options={'permissions': [('view_carbonemissions_avmfs', 'Can view carbon emissions'), ('add_carbonemissions_avmfs', 'Can add carbon emissions'), ('edit_carbonemissions_avmfs', 'Can edit carbon emissions'), ('delete_carbonemissions_avmfs', 'Can delete carbon emissions')]},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'permissions': [('view_communication_avmfs', 'Can view communication'), ('add_communication_avmfs', 'Can add communication'), ('edit_communication_avmfs', 'Can edit communication'), ('delete_communication_avmfs', 'Can delete communication')]},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_aircraft_avmfs', 'Can view aircraft'), ('edit_aircraft_avmfs', 'Can edit aircraft'), ('add_aircraft_avmfs', 'Can add aircraft'), ('delete_aircraft_avmfs', 'Can delete aircraft')]},
        ),
    ]
